# CircleCI configuration for Spectrum

# Aliases
aliases:

  # Cache Management
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - mobile/node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn
    |
      yarn
      yarn add global micro-dev
      cd ./servers/api && yarn && cd ../..
      cd ./servers/search && yarn && cd ../../

  - &setup-and-build-web
    name: Setup and build web
    command: yarn run build

  - &setup-and-build-search
    name: Setup and build search
    command: yarn run build:search

  - &start-api
    name: Start the API in the background
    command: yarn run dev:api
    background: true

  - &start-web
    name: Start web client in the background
    command: yarn run dev:web
    background: true

defaults: &defaults
  working_directory: ~/spec-next

js_defaults: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:8

macos_defaults: &macos_defaults
  <<: *defaults
  macos:
    xcode: "9.2.0"

version: 2
jobs:

  # Set up environment and install required dependencies
  checkout_environment:
    <<: *js_defaults
    steps:
      - checkout

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - persist_to_workspace:
          root: .
          paths: .

  # Start db and servers, then run e2e and unit tests
  test_web:
    <<: *defaults
    docker:
      - image: circleci/node:8-browsers
      - image: cypress/base:6
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/spec-next
      - run: *setup-and-build-web
      - run: *start-api
      - run: *start-web
      # Wait for the API and webserver to start
      - run: ./node_modules/.bin/wait-on http://localhost:3000 http://localhost:3001
      - run:
          name: Run E2E Tests
          command: yarn run test:e2e

  # Run eslint, flow etc.
  test_static_js:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spec-next
      - run:
          name: Run Flow
          command: yarn run flow

workflows:
  version: 2

  test:
    jobs:
      - checkout_environment
      
      - test_web:
          requires:
            - checkout_environment
      - test_static_js:
          requires:
            - checkout_environment